name: at_demo_data
description: A Dart library that contains test data, testable @‎sign credentials and demo environment variables that can be used for writing demo apps and testing with the local test environment.
homepage: https://www.atsign.dev
documentation: https://atsign.dev/docs.html
repository: https://github.com/atsign-foundation/at_demos

version: 0.0.3+1

environment:
  sdk: '>=2.7.0 <3.0.0'

#dependencies:

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
  test_cov: ^0.2.1
