name: at_demo_data
description: A library of data that contains demo enviroment variables and @sign
  credentials that can used for demo apps and testing
homepage: https://www.atsign.dev
documentation: https://atsign.dev/docs.html
repository: https://github.com/atsign-foundation/at_demos

version: 0.0.3+1

environment:
  sdk: '>=2.12.0 <3.0.0'

#dependencies:
dev_dependencies:
  test: ^1.17.10
  test_cov: ^1.0.1
