name: at_demo_data
description: A Dart library that contains test data, testable @‎sign credentials and demo environment variables that can be used for writing demo apps and testing with the local test environment.
homepage: https://www.atsign.dev
documentation: https://atsign.dev/docs/
repository: https://github.com/atsign-foundation/at_demos

version: 0.0.4

environment:
  sdk: '>=2.12.0 <3.0.0'

#dependencies:
dev_dependencies:
  test: ^1.17.10
  test_cov: ^1.0.1
